/*
 * STEPPER_MOTOR_prg.c
 *
 *  Created on: Mar 29, 2023
 *      Author: User
 */
#include"../../LIB/STD_Types.h"
#include"../../LIB/BIT_MATH.h"

#include"../../MCAL/DIO/DIO_int.h"
#include"STEPPER_MOTOR_cfg.h"
#include "STEPPER_MOTOR_int.h"
#include"STEPPER_MOTOR_prv.h"
#include<avr/delay.h>



void HSTEPPER_MOTOR_voidInit(void)
{
	MDIO_voidSetPinDirection(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN0,PIN_OUT);
	MDIO_voidSetPinDirection(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN1,PIN_OUT);
	MDIO_voidSetPinDirection(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN2,PIN_OUT);
	MDIO_voidSetPinDirection(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN3,PIN_OUT);

	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN0,PIN_HIGH);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN1,PIN_HIGH);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN2,PIN_HIGH);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN3,PIN_HIGH);

}

void  HSTEPPER_MOTOR_voidOneRevFullStepCW(void)
{
	u16 Local_STEPPER_counter;
	for(Local_STEPPER_counter=0;Local_STEPPER_counter<STEPPER_MOTOR_ITERATION;Local_STEPPER_counter++)
	{
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN0,PIN_HIGH);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN1,PIN_LOW);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN2,PIN_LOW);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN3,PIN_LOW);
	_delay_ms(3);

	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN0,PIN_LOW);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN1,PIN_HIGH);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN2,PIN_LOW);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN3,PIN_LOW);
	_delay_ms(3);

	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN0,PIN_LOW);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN1,PIN_LOW);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN2,PIN_HIGH);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN3,PIN_LOW);
	_delay_ms(3);

	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN0,PIN_LOW);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN1,PIN_LOW);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN2,PIN_LOW);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN3,PIN_HIGH);
	_delay_ms(3);
	}
}

void  HSTEPPER_MOTOR_voidOneRevFullStepUNCW(void)
{
	u16 Local_STEPPER_counter;
	for(Local_STEPPER_counter=0;Local_STEPPER_counter<STEPPER_MOTOR_ITERATION;Local_STEPPER_counter++)
	{
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN0,PIN_LOW);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN1,PIN_LOW);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN2,PIN_LOW);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN3,PIN_HIGH);
	_delay_ms(3);

	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN0,PIN_LOW);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN1,PIN_LOW);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN2,PIN_HIGH);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN3,PIN_LOW);
	_delay_ms(3);

	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN0,PIN_LOW);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN1,PIN_HIGH);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN2,PIN_LOW);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN3,PIN_LOW);
	_delay_ms(3);

	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN0,PIN_HIGH);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN1,PIN_LOW);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN2,PIN_LOW);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN3,PIN_LOW);
	_delay_ms(3);
	}
}

void  HSTEPPER_MOTOR_voidSpecificFullStepUNCW(u16 Degree)
{
	u16 Local_STEPPER_counter;
	u16 Local_STEPPER_Specific= ((Degree/11.25)*64)/4;
	for(Local_STEPPER_counter=0;Local_STEPPER_counter<Local_STEPPER_Specific;Local_STEPPER_counter++)
	{
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN0,PIN_LOW);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN1,PIN_LOW);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN2,PIN_LOW);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN3,PIN_HIGH);
	_delay_ms(3);

	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN0,PIN_LOW);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN1,PIN_LOW);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN2,PIN_HIGH);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN3,PIN_LOW);
	_delay_ms(3);

	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN0,PIN_LOW);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN1,PIN_HIGH);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN2,PIN_LOW);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN3,PIN_LOW);
	_delay_ms(3);

	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN0,PIN_HIGH);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN1,PIN_LOW);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN2,PIN_LOW);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN3,PIN_LOW);
	_delay_ms(3);
	}
}

void  HSTEPPER_MOTOR_voidSpecificFullStepCW(u16 Degree)
{
	u16 Local_STEPPER_counter;
	u16 Local_STEPPER_Specific= ((Degree/11.25)*64)/4;
	for(Local_STEPPER_counter=0;Local_STEPPER_counter<Local_STEPPER_Specific;Local_STEPPER_counter++)
	{
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN0,PIN_HIGH);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN1,PIN_LOW);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN2,PIN_LOW);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN3,PIN_LOW);
	_delay_ms(3);

	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN0,PIN_LOW);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN1,PIN_HIGH);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN2,PIN_LOW);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN3,PIN_LOW);
	_delay_ms(3);

	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN0,PIN_LOW);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN1,PIN_LOW);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN2,PIN_HIGH);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN3,PIN_LOW);
	_delay_ms(3);

	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN0,PIN_LOW);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN1,PIN_LOW);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN2,PIN_LOW);
	MDIO_voidSetPinValue(STEPPER_MOTOR_PORT,STEPPER_MOTOR_PIN3,PIN_HIGH);
	_delay_ms(3);
	}
}



